sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
          language: python
          python: 3.6
        - os: osx
          osx_image: xcode8.3
          language: generic
    allow_failures:
        - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./dependencies_osx.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dependencies_ubuntu.sh ; fi

script:
    - cd core/ydk
    - mkdir -p build && cd build && cmake .. && make &> /dev/null && sudo make install && make test

    - cd ../../../ietf
    - mkdir -p build && cd build && cmake .. && make &> /dev/null && sudo make install

    - cd ../../openconfig
    - mkdir -p build && cd build && cmake .. && make &> /dev/null && sudo make install

#   - cd ../../cisco-nx-os
#   - mkdir -p build && cd build && cmake .. && make &> /dev/null && sudo make install
