sudo: required

matrix:
    include:
        - os: linux
          dist: bionic
          language: generic
        - os: osx
          osx_image: xcode8.3
          language: generic
    allow_failures:
        - os: osx

before_install:
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./dependencies_osx.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dependencies_ubuntu.sh ; fi

script:
    - cd core/ydk
    - mkdir -p build && cd build && cmake .. && sudo make install test

    - cd ../../../ietf
    - mkdir -p build && cd build && cmake .. && sudo make install

    - cd ../../openconfig
    - mkdir -p build && cd build && cmake .. && sudo make install

    - cd ../../cisco-nx-os
    - mkdir -p build && cd build && cmake .. && sudo make install
