#ifndef _CISCO_IOS_XE_IOS_COMMON_OPER_
#define _CISCO_IOS_XE_IOS_COMMON_OPER_

#include <memory>
#include <vector>
#include <string>
#include <ydk/types.hpp>
#include <ydk/errors.hpp>

namespace cisco_ios_xe {
namespace Cisco_IOS_XE_ios_common_oper {

class IosLinktype : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf ios_linktype_illegal;
        static const ydk::Enum::YLeaf ios_linktype_arp;
        static const ydk::Enum::YLeaf ios_linktype_rarp;
        static const ydk::Enum::YLeaf ios_linktype_xarp;
        static const ydk::Enum::YLeaf ios_linktype_probe;
        static const ydk::Enum::YLeaf ios_linktype_loop;
        static const ydk::Enum::YLeaf ios_linktype_address;
        static const ydk::Enum::YLeaf ios_linktype_ip;
        static const ydk::Enum::YLeaf ios_linktype_pup;
        static const ydk::Enum::YLeaf ios_linktype_9_unused;
        static const ydk::Enum::YLeaf ios_linktype_xns;
        static const ydk::Enum::YLeaf ios_linktype_novell;
        static const ydk::Enum::YLeaf ios_linktype_apollo;
        static const ydk::Enum::YLeaf ios_linktype_vines;
        static const ydk::Enum::YLeaf ios_linktype_pad;
        static const ydk::Enum::YLeaf ios_linktype_x25;
        static const ydk::Enum::YLeaf ios_linktype_appletalk;
        static const ydk::Enum::YLeaf ios_linktype_aarp;
        static const ydk::Enum::YLeaf ios_linktype_dec_spanning;
        static const ydk::Enum::YLeaf ios_linktype_ieee_spanning;
        static const ydk::Enum::YLeaf ios_linktype_nbf;
        static const ydk::Enum::YLeaf ios_linktype_21_unused;
        static const ydk::Enum::YLeaf ios_linktype_decnet;
        static const ydk::Enum::YLeaf ios_linktype_decnet_router_l1;
        static const ydk::Enum::YLeaf ios_linktype_decnet_node;
        static const ydk::Enum::YLeaf ios_linktype_clns;
        static const ydk::Enum::YLeaf ios_linktype_clns_all_es;
        static const ydk::Enum::YLeaf ios_linktype_clns_all_is;
        static const ydk::Enum::YLeaf ios_linktype_clns_bcast;
        static const ydk::Enum::YLeaf ios_linktype_xot;
        static const ydk::Enum::YLeaf ios_linktype_ppp;
        static const ydk::Enum::YLeaf ios_linktype_lat;
        static const ydk::Enum::YLeaf ios_linktype_vines_echo;
        static const ydk::Enum::YLeaf ios_linktype_vines_loop;
        static const ydk::Enum::YLeaf ios_linktype_atalk_short;
        static const ydk::Enum::YLeaf ios_linktype_mop_boot;
        static const ydk::Enum::YLeaf ios_linktype_mop_console;
        static const ydk::Enum::YLeaf ios_linktype_rsrb;
        static const ydk::Enum::YLeaf ios_linktype_bridge;
        static const ydk::Enum::YLeaf ios_linktype_stun;
        static const ydk::Enum::YLeaf ios_linktype_fr_arp;
        static const ydk::Enum::YLeaf ios_linktype_smds_arp;
        static const ydk::Enum::YLeaf ios_linktype_mac;
        static const ydk::Enum::YLeaf ios_linktype_ibmnm;
        static const ydk::Enum::YLeaf ios_linktype_uarp;
        static const ydk::Enum::YLeaf ios_linktype_ultra_hello;
        static const ydk::Enum::YLeaf ios_linktype_x25service;
        static const ydk::Enum::YLeaf ios_linktype_uncompressed_tcp;
        static const ydk::Enum::YLeaf ios_linktype_compressed_tcp;
        static const ydk::Enum::YLeaf ios_linktype_llc2;
        static const ydk::Enum::YLeaf ios_linktype_cmns;
        static const ydk::Enum::YLeaf ios_linktype_isis_all_l1_is;
        static const ydk::Enum::YLeaf ios_linktype_isis_all_l2_is;
        static const ydk::Enum::YLeaf ios_linktype_fr_switch;
        static const ydk::Enum::YLeaf ios_linktype_decnet_prime_router;
        static const ydk::Enum::YLeaf ios_linktype_srb;
        static const ydk::Enum::YLeaf ios_linktype_qllc;
        static const ydk::Enum::YLeaf ios_linktype_x25_multi_enc;
        static const ydk::Enum::YLeaf ios_linktype_lex;
        static const ydk::Enum::YLeaf ios_linktype_lex_rcmd;
        static const ydk::Enum::YLeaf ios_linktype_decnet_router_l2;
        static const ydk::Enum::YLeaf ios_linktype_cls;
        static const ydk::Enum::YLeaf ios_linktype_snapshot;
        static const ydk::Enum::YLeaf ios_linktype_dlsw;
        static const ydk::Enum::YLeaf ios_linktype_sde;
        static const ydk::Enum::YLeaf ios_linktype_cdp;
        static const ydk::Enum::YLeaf ios_linktype_ppp_compression;
        static const ydk::Enum::YLeaf ios_linktype_nmp;
        static const ydk::Enum::YLeaf ios_linktype_bstun;
        static const ydk::Enum::YLeaf ios_linktype_ipc;
        static const ydk::Enum::YLeaf ios_linktype_love;
        static const ydk::Enum::YLeaf ios_linktype_cfgack;
        static const ydk::Enum::YLeaf ios_linktype_appn_anr;
        static const ydk::Enum::YLeaf ios_linktype_multilink;
        static const ydk::Enum::YLeaf ios_linktype_nhrp;
        static const ydk::Enum::YLeaf ios_linktype_mac_exp;
        static const ydk::Enum::YLeaf ios_linktype_cgmp;
        static const ydk::Enum::YLeaf ios_linktype_vtp;
        static const ydk::Enum::YLeaf ios_linktype_cpp;
        static const ydk::Enum::YLeaf ios_linktype_ipv6;
        static const ydk::Enum::YLeaf ios_linktype_atm;
        static const ydk::Enum::YLeaf ios_linktype_isl;
        static const ydk::Enum::YLeaf ios_linktype_bap;
        static const ydk::Enum::YLeaf ios_linktype_compressed_rtp;
        static const ydk::Enum::YLeaf ios_linktype_compressed_udp;
        static const ydk::Enum::YLeaf ios_linktype_uncompressed_udp;
        static const ydk::Enum::YLeaf ios_linktype_context_status;
        static const ydk::Enum::YLeaf ios_linktype_fr_switch_serial;
        static const ydk::Enum::YLeaf ios_linktype_c5_ibipc;
        static const ydk::Enum::YLeaf ios_linktype_nlsp_multicast;
        static const ydk::Enum::YLeaf ios_linktype_tag;
        static const ydk::Enum::YLeaf ios_linktype_mtag;
        static const ydk::Enum::YLeaf ios_linktype_alps;
        static const ydk::Enum::YLeaf ios_linktype_drip;
        static const ydk::Enum::YLeaf ios_linktype_voice;
        static const ydk::Enum::YLeaf ios_linktype_fr_atm;
        static const ydk::Enum::YLeaf ios_linktype_fcp;
        static const ydk::Enum::YLeaf ios_linktype_voice_no_rt;
        static const ydk::Enum::YLeaf ios_linktype_vlan_br_spanning;
        static const ydk::Enum::YLeaf ios_linktype_dot1q;
        static const ydk::Enum::YLeaf ios_linktype_cisco_ipc;
        static const ydk::Enum::YLeaf ios_linktype_vsi;
        static const ydk::Enum::YLeaf ios_linktype_isdn_manual_call;
        static const ydk::Enum::YLeaf ios_linktype_comp_non_tcp;
        static const ydk::Enum::YLeaf ios_linktype_comp_tcp_nodelta;
        static const ydk::Enum::YLeaf ios_linktype_fr_atm_srv;
        static const ydk::Enum::YLeaf ios_linktype_fr_eek;
        static const ydk::Enum::YLeaf ios_linktype_ehsa;
        static const ydk::Enum::YLeaf ios_linktype_mscp;
        static const ydk::Enum::YLeaf ios_linktype_scp;
        static const ydk::Enum::YLeaf ios_linktype_pppoe_discovery;
        static const ydk::Enum::YLeaf ios_linktype_pppoe_session;
        static const ydk::Enum::YLeaf ios_linktype_l2rly;
        static const ydk::Enum::YLeaf ios_linktype_gtp;
        static const ydk::Enum::YLeaf ios_linktype_comp_rtp_16;
        static const ydk::Enum::YLeaf ios_linktype_comp_udp_16;
        static const ydk::Enum::YLeaf ios_linktype_atm_switch;
        static const ydk::Enum::YLeaf ios_linktype_pagp;
        static const ydk::Enum::YLeaf ios_linktype_sstp;
        static const ydk::Enum::YLeaf ios_linktype_rlq_req;
        static const ydk::Enum::YLeaf ios_linktype_rlq_resp;
        static const ydk::Enum::YLeaf ios_linktype_dyntrk;
        static const ydk::Enum::YLeaf ios_linktype_mls_ip;
        static const ydk::Enum::YLeaf ios_linktype_dyntrk_encap;
        static const ydk::Enum::YLeaf ios_linktype_udld;
        static const ydk::Enum::YLeaf ios_linktype_srp;
        static const ydk::Enum::YLeaf ios_linktype_rgmp;
        static const ydk::Enum::YLeaf ios_linktype_mistp;
        static const ydk::Enum::YLeaf ios_linktype_compressed_fr;
        static const ydk::Enum::YLeaf ios_linktype_vito_scp;
        static const ydk::Enum::YLeaf ios_linktype_const_ftep;
        static const ydk::Enum::YLeaf ios_linktype_vlan_switch;
        static const ydk::Enum::YLeaf ios_linktype_atom;
        static const ydk::Enum::YLeaf ios_linktype_raw;
        static const ydk::Enum::YLeaf ios_linktype_oscp;
        static const ydk::Enum::YLeaf ios_linktype_diag;
        static const ydk::Enum::YLeaf ios_linktype_stack_disc;
        static const ydk::Enum::YLeaf ios_linktype_fast_trans;
        static const ydk::Enum::YLeaf ios_linktype_dot1x;
        static const ydk::Enum::YLeaf ios_linktype_fr_frag;
        static const ydk::Enum::YLeaf ios_linktype_slow_proto;
        static const ydk::Enum::YLeaf ios_linktype_eompls;
        static const ydk::Enum::YLeaf ios_linktype_ieee_dot1q;
        static const ydk::Enum::YLeaf ios_linktype_voice_nrt;
        static const ydk::Enum::YLeaf ios_linktype_uti_raw;
        static const ydk::Enum::YLeaf ios_linktype_hdlc_hapi;
        static const ydk::Enum::YLeaf ios_linktype_cwan_ipsec;
        static const ydk::Enum::YLeaf ios_linktype_sstp_spanning;
        static const ydk::Enum::YLeaf ios_linktype_fr_saa;
        static const ydk::Enum::YLeaf ios_linktype_froe;
        static const ydk::Enum::YLeaf ios_linktype_vpdn;
        static const ydk::Enum::YLeaf ios_linktype_slm_saa;
        static const ydk::Enum::YLeaf ios_linktype_rf_kpa;
        static const ydk::Enum::YLeaf ios_linktype_rbcp;
        static const ydk::Enum::YLeaf ios_linktype_p2ipc;
        static const ydk::Enum::YLeaf ios_linktype_p2ipc_mpls;
        static const ydk::Enum::YLeaf ios_linktype_xconnect;
        static const ydk::Enum::YLeaf ios_linktype_slm_fr_saa;
        static const ydk::Enum::YLeaf ios_linktype_cdma_rp;
        static const ydk::Enum::YLeaf ios_linktype_pw_ip_deprecated;
        static const ydk::Enum::YLeaf ios_linktype_vj_uncomp_tcp;
        static const ydk::Enum::YLeaf ios_linktype_vj_comp_tcp;
        static const ydk::Enum::YLeaf ios_linktype_online_diags;
        static const ydk::Enum::YLeaf ios_linktype_vrf_ipsec;
        static const ydk::Enum::YLeaf ios_linktype_broadcom;
        static const ydk::Enum::YLeaf ios_linktype_http;
        static const ydk::Enum::YLeaf ios_linktype_lfp;
        static const ydk::Enum::YLeaf ios_linktype_drprip;
        static const ydk::Enum::YLeaf ios_linktype_ether_cfm;
        static const ydk::Enum::YLeaf ios_linktype_ether_oam;
        static const ydk::Enum::YLeaf ios_linktype_mmu;
        static const ydk::Enum::YLeaf ios_linktype_vslp;
        static const ydk::Enum::YLeaf ios_linktype_ether_lmi;
        static const ydk::Enum::YLeaf ios_linktype_lldp;
        static const ydk::Enum::YLeaf ios_linktype_gvrp;
        static const ydk::Enum::YLeaf ios_linktype_gmrp;
        static const ydk::Enum::YLeaf ios_linktype_ancp;
        static const ydk::Enum::YLeaf ios_linktype_rep;
        static const ydk::Enum::YLeaf ios_linktype_rep_hfl;
        static const ydk::Enum::YLeaf ios_linktype_ipe;
        static const ydk::Enum::YLeaf ios_linktype_mvrp;
        static const ydk::Enum::YLeaf ios_linktype_vsda;
        static const ydk::Enum::YLeaf ios_linktype_ecfm;
        static const ydk::Enum::YLeaf ios_linktype_dot1ah;
        static const ydk::Enum::YLeaf ios_linktype_sdp;
        static const ydk::Enum::YLeaf ios_linktype_cdpfwd;
        static const ydk::Enum::YLeaf ios_linktype_t101;
        static const ydk::Enum::YLeaf ios_linktype_rsvp;
        static const ydk::Enum::YLeaf ios_linktype_isisl2_otv_all_l1_is;
        static const ydk::Enum::YLeaf ios_linktype_isisl2_otv_all_l2_is;
        static const ydk::Enum::YLeaf ios_linktype_g8032;
        static const ydk::Enum::YLeaf ios_linktype_sdac;
        static const ydk::Enum::YLeaf ios_linktype_ptppd;
        static const ydk::Enum::YLeaf ios_linktype_rawtcp;
        static const ydk::Enum::YLeaf ios_linktype_an_ch;
        static const ydk::Enum::YLeaf ios_linktype_fex_sdp;
        static const ydk::Enum::YLeaf ios_linktype_esmc;
        static const ydk::Enum::YLeaf ios_linktype_cisp;
        static const ydk::Enum::YLeaf ios_linktype_async;
        static const ydk::Enum::YLeaf ios_linktype_msrp;
        static const ydk::Enum::YLeaf ios_linktype_macsec_post_exp;
        static const ydk::Enum::YLeaf ios_linktype_macsec_sectag;

        static int get_enum_value(const std::string & name) {
            if (name == "ios-linktype-illegal") return 0;
            if (name == "ios-linktype-arp") return 1;
            if (name == "ios-linktype-rarp") return 2;
            if (name == "ios-linktype-xarp") return 3;
            if (name == "ios-linktype-probe") return 4;
            if (name == "ios-linktype-loop") return 5;
            if (name == "ios-linktype-address") return 6;
            if (name == "ios-linktype-ip") return 7;
            if (name == "ios-linktype-pup") return 8;
            if (name == "ios-linktype-9-unused") return 9;
            if (name == "ios-linktype-xns") return 10;
            if (name == "ios-linktype-novell") return 11;
            if (name == "ios-linktype-apollo") return 12;
            if (name == "ios-linktype-vines") return 13;
            if (name == "ios-linktype-pad") return 14;
            if (name == "ios-linktype-x25") return 15;
            if (name == "ios-linktype-appletalk") return 16;
            if (name == "ios-linktype-aarp") return 17;
            if (name == "ios-linktype-dec-spanning") return 18;
            if (name == "ios-linktype-ieee-spanning") return 19;
            if (name == "ios-linktype-nbf") return 20;
            if (name == "ios-linktype-21-unused") return 21;
            if (name == "ios-linktype-decnet") return 22;
            if (name == "ios-linktype-decnet-router-l1") return 23;
            if (name == "ios-linktype-decnet-node") return 24;
            if (name == "ios-linktype-clns") return 25;
            if (name == "ios-linktype-clns-all-es") return 26;
            if (name == "ios-linktype-clns-all-is") return 27;
            if (name == "ios-linktype-clns-bcast") return 28;
            if (name == "ios-linktype-xot") return 29;
            if (name == "ios-linktype-ppp") return 30;
            if (name == "ios-linktype-lat") return 31;
            if (name == "ios-linktype-vines-echo") return 32;
            if (name == "ios-linktype-vines-loop") return 33;
            if (name == "ios-linktype-atalk-short") return 34;
            if (name == "ios-linktype-mop-boot") return 35;
            if (name == "ios-linktype-mop-console") return 36;
            if (name == "ios-linktype-rsrb") return 37;
            if (name == "ios-linktype-bridge") return 38;
            if (name == "ios-linktype-stun") return 39;
            if (name == "ios-linktype-fr-arp") return 40;
            if (name == "ios-linktype-smds-arp") return 41;
            if (name == "ios-linktype-mac") return 42;
            if (name == "ios-linktype-ibmnm") return 43;
            if (name == "ios-linktype-uarp") return 44;
            if (name == "ios-linktype-ultra-hello") return 45;
            if (name == "ios-linktype-x25service") return 46;
            if (name == "ios-linktype-uncompressed-tcp") return 47;
            if (name == "ios-linktype-compressed-tcp") return 48;
            if (name == "ios-linktype-llc2") return 49;
            if (name == "ios-linktype-cmns") return 50;
            if (name == "ios-linktype-isis-all-l1-is") return 51;
            if (name == "ios-linktype-isis-all-l2-is") return 52;
            if (name == "ios-linktype-fr-switch") return 53;
            if (name == "ios-linktype-decnet-prime-router") return 54;
            if (name == "ios-linktype-srb") return 55;
            if (name == "ios-linktype-qllc") return 56;
            if (name == "ios-linktype-x25-multi-enc") return 57;
            if (name == "ios-linktype-lex") return 58;
            if (name == "ios-linktype-lex-rcmd") return 59;
            if (name == "ios-linktype-decnet-router-l2") return 60;
            if (name == "ios-linktype-cls") return 61;
            if (name == "ios-linktype-snapshot") return 62;
            if (name == "ios-linktype-dlsw") return 63;
            if (name == "ios-linktype-sde") return 64;
            if (name == "ios-linktype-cdp") return 65;
            if (name == "ios-linktype-ppp-compression") return 66;
            if (name == "ios-linktype-nmp") return 67;
            if (name == "ios-linktype-bstun") return 68;
            if (name == "ios-linktype-ipc") return 69;
            if (name == "ios-linktype-love") return 70;
            if (name == "ios-linktype-cfgack") return 71;
            if (name == "ios-linktype-appn-anr") return 72;
            if (name == "ios-linktype-multilink") return 73;
            if (name == "ios-linktype-nhrp") return 74;
            if (name == "ios-linktype-mac-exp") return 75;
            if (name == "ios-linktype-cgmp") return 76;
            if (name == "ios-linktype-vtp") return 77;
            if (name == "ios-linktype-cpp") return 78;
            if (name == "ios-linktype-ipv6") return 79;
            if (name == "ios-linktype-atm") return 80;
            if (name == "ios-linktype-isl") return 81;
            if (name == "ios-linktype-bap") return 82;
            if (name == "ios-linktype-compressed-rtp") return 83;
            if (name == "ios-linktype-compressed-udp") return 84;
            if (name == "ios-linktype-uncompressed-udp") return 85;
            if (name == "ios-linktype-context-status") return 86;
            if (name == "ios-linktype-fr-switch-serial") return 87;
            if (name == "ios-linktype-c5-ibipc") return 88;
            if (name == "ios-linktype-nlsp-multicast") return 89;
            if (name == "ios-linktype-tag") return 90;
            if (name == "ios-linktype-mtag") return 91;
            if (name == "ios-linktype-alps") return 92;
            if (name == "ios-linktype-drip") return 93;
            if (name == "ios-linktype-voice") return 94;
            if (name == "ios-linktype-fr-atm") return 95;
            if (name == "ios-linktype-fcp") return 96;
            if (name == "ios-linktype-voice-no-rt") return 97;
            if (name == "ios-linktype-vlan-br-spanning") return 98;
            if (name == "ios-linktype-dot1q") return 99;
            if (name == "ios-linktype-cisco-ipc") return 100;
            if (name == "ios-linktype-vsi") return 101;
            if (name == "ios-linktype-isdn-manual-call") return 102;
            if (name == "ios-linktype-comp-non-tcp") return 103;
            if (name == "ios-linktype-comp-tcp-nodelta") return 104;
            if (name == "ios-linktype-fr-atm-srv") return 105;
            if (name == "ios-linktype-fr-eek") return 106;
            if (name == "ios-linktype-ehsa") return 107;
            if (name == "ios-linktype-mscp") return 108;
            if (name == "ios-linktype-scp") return 109;
            if (name == "ios-linktype-pppoe-discovery") return 110;
            if (name == "ios-linktype-pppoe-session") return 111;
            if (name == "ios-linktype-l2rly") return 112;
            if (name == "ios-linktype-gtp") return 113;
            if (name == "ios-linktype-comp-rtp-16") return 114;
            if (name == "ios-linktype-comp-udp-16") return 115;
            if (name == "ios-linktype-atm-switch") return 116;
            if (name == "ios-linktype-pagp") return 117;
            if (name == "ios-linktype-sstp") return 118;
            if (name == "ios-linktype-rlq-req") return 119;
            if (name == "ios-linktype-rlq-resp") return 120;
            if (name == "ios-linktype-dyntrk") return 121;
            if (name == "ios-linktype-mls-ip") return 122;
            if (name == "ios-linktype-dyntrk-encap") return 123;
            if (name == "ios-linktype-udld") return 124;
            if (name == "ios-linktype-srp") return 125;
            if (name == "ios-linktype-rgmp") return 126;
            if (name == "ios-linktype-mistp") return 127;
            if (name == "ios-linktype-compressed-fr") return 128;
            if (name == "ios-linktype-vito-scp") return 129;
            if (name == "ios-linktype-const-ftep") return 130;
            if (name == "ios-linktype-vlan-switch") return 131;
            if (name == "ios-linktype-atom") return 132;
            if (name == "ios-linktype-raw") return 133;
            if (name == "ios-linktype-oscp") return 134;
            if (name == "ios-linktype-diag") return 135;
            if (name == "ios-linktype-stack-disc") return 136;
            if (name == "ios-linktype-fast-trans") return 137;
            if (name == "ios-linktype-dot1x") return 138;
            if (name == "ios-linktype-fr-frag") return 139;
            if (name == "ios-linktype-slow-proto") return 140;
            if (name == "ios-linktype-eompls") return 141;
            if (name == "ios-linktype-ieee-dot1q") return 142;
            if (name == "ios-linktype-voice-nrt") return 143;
            if (name == "ios-linktype-uti-raw") return 144;
            if (name == "ios-linktype-hdlc-hapi") return 145;
            if (name == "ios-linktype-cwan-ipsec") return 146;
            if (name == "ios-linktype-sstp-spanning") return 147;
            if (name == "ios-linktype-fr-saa") return 148;
            if (name == "ios-linktype-froe") return 149;
            if (name == "ios-linktype-vpdn") return 150;
            if (name == "ios-linktype-slm-saa") return 151;
            if (name == "ios-linktype-rf-kpa") return 152;
            if (name == "ios-linktype-rbcp") return 153;
            if (name == "ios-linktype-p2ipc") return 154;
            if (name == "ios-linktype-p2ipc-mpls") return 155;
            if (name == "ios-linktype-xconnect") return 156;
            if (name == "ios-linktype-slm-fr-saa") return 157;
            if (name == "ios-linktype-cdma-rp") return 158;
            if (name == "ios-linktype-pw-ip-deprecated") return 159;
            if (name == "ios-linktype-vj-uncomp-tcp") return 160;
            if (name == "ios-linktype-vj-comp-tcp") return 161;
            if (name == "ios-linktype-online-diags") return 162;
            if (name == "ios-linktype-vrf-ipsec") return 163;
            if (name == "ios-linktype-broadcom") return 164;
            if (name == "ios-linktype-http") return 165;
            if (name == "ios-linktype-lfp") return 166;
            if (name == "ios-linktype-drprip") return 167;
            if (name == "ios-linktype-ether-cfm") return 168;
            if (name == "ios-linktype-ether-oam") return 169;
            if (name == "ios-linktype-mmu") return 170;
            if (name == "ios-linktype-vslp") return 171;
            if (name == "ios-linktype-ether-lmi") return 172;
            if (name == "ios-linktype-lldp") return 173;
            if (name == "ios-linktype-gvrp") return 174;
            if (name == "ios-linktype-gmrp") return 175;
            if (name == "ios-linktype-ancp") return 176;
            if (name == "ios-linktype-rep") return 177;
            if (name == "ios-linktype-rep-hfl") return 178;
            if (name == "ios-linktype-ipe") return 179;
            if (name == "ios-linktype-mvrp") return 180;
            if (name == "ios-linktype-vsda") return 181;
            if (name == "ios-linktype-ecfm") return 182;
            if (name == "ios-linktype-dot1ah") return 183;
            if (name == "ios-linktype-sdp") return 184;
            if (name == "ios-linktype-cdpfwd") return 185;
            if (name == "ios-linktype-t101") return 186;
            if (name == "ios-linktype-rsvp") return 187;
            if (name == "ios-linktype-isisl2-otv-all-l1-is") return 188;
            if (name == "ios-linktype-isisl2-otv-all-l2-is") return 189;
            if (name == "ios-linktype-g8032") return 190;
            if (name == "ios-linktype-sdac") return 191;
            if (name == "ios-linktype-ptppd") return 192;
            if (name == "ios-linktype-rawtcp") return 193;
            if (name == "ios-linktype-an-ch") return 194;
            if (name == "ios-linktype-fex-sdp") return 195;
            if (name == "ios-linktype-esmc") return 196;
            if (name == "ios-linktype-cisp") return 197;
            if (name == "ios-linktype-async") return 198;
            if (name == "ios-linktype-msrp") return 199;
            if (name == "ios-linktype-macsec-post-exp") return 200;
            if (name == "ios-linktype-macsec-sectag") return 201;
            return -1;
        }
};

class IosSnpaType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf ios_snpa_type_illegal;
        static const ydk::Enum::YLeaf ios_snpa_type_ieee48;
        static const ydk::Enum::YLeaf ios_snpa_type_ieee16;
        static const ydk::Enum::YLeaf ios_snpa_type_xerox;
        static const ydk::Enum::YLeaf ios_snpa_type_x121;
        static const ydk::Enum::YLeaf ios_snpa_type_cisco_hdlc;
        static const ydk::Enum::YLeaf ios_snpa_type_cisco_mlapb;
        static const ydk::Enum::YLeaf ios_snpa_type_lapb;
        static const ydk::Enum::YLeaf ios_snpa_type_smds48;
        static const ydk::Enum::YLeaf ios_snpa_type_cisco_msdlc;
        static const ydk::Enum::YLeaf ios_snpa_type_fr10;
        static const ydk::Enum::YLeaf ios_snpa_type_ultra;
        static const ydk::Enum::YLeaf ios_snpa_type_cisco_tunnel;
        static const ydk::Enum::YLeaf ios_snpa_type_cisco_ctunnel;
        static const ydk::Enum::YLeaf ios_snpa_type_rrr_tunnel;
        static const ydk::Enum::YLeaf ios_snpa_type_ppp;
        static const ydk::Enum::YLeaf ios_snpa_type_smds64;
        static const ydk::Enum::YLeaf ios_snpa_type_atmvc;
        static const ydk::Enum::YLeaf ios_snpa_type_atm_bundle;
        static const ydk::Enum::YLeaf ios_snpa_type_atm_svc_bundle;
        static const ydk::Enum::YLeaf ios_snpa_type_atmnsap;
        static const ydk::Enum::YLeaf ios_snpa_type_atm_e164;
        static const ydk::Enum::YLeaf ios_snpa_type_atm_userspecified;
        static const ydk::Enum::YLeaf ios_snpa_type_sdlc;
        static const ydk::Enum::YLeaf ios_snpa_type_x25pvc;
        static const ydk::Enum::YLeaf ios_snpa_type_lapd;
        static const ydk::Enum::YLeaf ios_snpa_type_masked_atmnsap;
        static const ydk::Enum::YLeaf ios_snpa_type_atmesi;
        static const ydk::Enum::YLeaf ios_snpa_type_slip;
        static const ydk::Enum::YLeaf ios_snpa_type_routedesc;
        static const ydk::Enum::YLeaf ios_snpa_type_srp_outer;
        static const ydk::Enum::YLeaf ios_snpa_type_srp_inner;

        static int get_enum_value(const std::string & name) {
            if (name == "ios-snpa-type-illegal") return 0;
            if (name == "ios-snpa-type-ieee48") return 1;
            if (name == "ios-snpa-type-ieee16") return 2;
            if (name == "ios-snpa-type-xerox") return 3;
            if (name == "ios-snpa-type-x121") return 4;
            if (name == "ios-snpa-type-cisco-hdlc") return 5;
            if (name == "ios-snpa-type-cisco-mlapb") return 6;
            if (name == "ios-snpa-type-lapb") return 7;
            if (name == "ios-snpa-type-smds48") return 8;
            if (name == "ios-snpa-type-cisco-msdlc") return 9;
            if (name == "ios-snpa-type-fr10") return 10;
            if (name == "ios-snpa-type-ultra") return 11;
            if (name == "ios-snpa-type-cisco-tunnel") return 12;
            if (name == "ios-snpa-type-cisco-ctunnel") return 13;
            if (name == "ios-snpa-type-rrr-tunnel") return 14;
            if (name == "ios-snpa-type-ppp") return 15;
            if (name == "ios-snpa-type-smds64") return 16;
            if (name == "ios-snpa-type-atmvc") return 17;
            if (name == "ios-snpa-type-atm-bundle") return 18;
            if (name == "ios-snpa-type-atm-svc-bundle") return 19;
            if (name == "ios-snpa-type-atmnsap") return 20;
            if (name == "ios-snpa-type-atm-e164") return 21;
            if (name == "ios-snpa-type-atm-userspecified") return 22;
            if (name == "ios-snpa-type-sdlc") return 23;
            if (name == "ios-snpa-type-x25pvc") return 24;
            if (name == "ios-snpa-type-lapd") return 25;
            if (name == "ios-snpa-type-masked-atmnsap") return 26;
            if (name == "ios-snpa-type-atmesi") return 27;
            if (name == "ios-snpa-type-slip") return 28;
            if (name == "ios-snpa-type-routedesc") return 29;
            if (name == "ios-snpa-type-srp-outer") return 30;
            if (name == "ios-snpa-type-srp-inner") return 31;
            return -1;
        }
};

class IosEncapsType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf ios_encaps_type_null;
        static const ydk::Enum::YLeaf ios_encaps_type_arpa;
        static const ydk::Enum::YLeaf ios_encaps_type_sap;
        static const ydk::Enum::YLeaf ios_encaps_type_snap;
        static const ydk::Enum::YLeaf ios_encaps_type_1822;
        static const ydk::Enum::YLeaf ios_encaps_type_hdlc;
        static const ydk::Enum::YLeaf ios_encaps_type_unused2;
        static const ydk::Enum::YLeaf ios_encaps_type_unused1;
        static const ydk::Enum::YLeaf ios_encaps_type_lapb;
        static const ydk::Enum::YLeaf ios_encaps_type_x25;
        static const ydk::Enum::YLeaf ios_encaps_type_hub;
        static const ydk::Enum::YLeaf ios_encaps_type_novell_ether;
        static const ydk::Enum::YLeaf ios_encaps_type_unsupported;
        static const ydk::Enum::YLeaf ios_encaps_type_3com_tr;
        static const ydk::Enum::YLeaf ios_encaps_type_ub_tr;
        static const ydk::Enum::YLeaf ios_encaps_type_apollo;
        static const ydk::Enum::YLeaf ios_encaps_type_ppp;
        static const ydk::Enum::YLeaf ios_encaps_type_unused4;
        static const ydk::Enum::YLeaf ios_encaps_type_vines_tr;
        static const ydk::Enum::YLeaf ios_encaps_type_ethertalk;
        static const ydk::Enum::YLeaf ios_encaps_type_frame_relay;
        static const ydk::Enum::YLeaf ios_encaps_type_smds;
        static const ydk::Enum::YLeaf ios_encaps_type_mac;
        static const ydk::Enum::YLeaf ios_encaps_type_ultra_iso2;
        static const ydk::Enum::YLeaf ios_encaps_type_ultra_iso1;
        static const ydk::Enum::YLeaf ios_encaps_type_stun;
        static const ydk::Enum::YLeaf ios_encaps_type_bridge;
        static const ydk::Enum::YLeaf ios_encaps_type_llc2;
        static const ydk::Enum::YLeaf ios_encaps_type_sdlcp;
        static const ydk::Enum::YLeaf ios_encaps_type_sdlcs;
        static const ydk::Enum::YLeaf ios_encaps_type_slip;
        static const ydk::Enum::YLeaf ios_encaps_type_tunnel;
        static const ydk::Enum::YLeaf ios_encaps_type_bridge_encaps;
        static const ydk::Enum::YLeaf ios_encaps_type_atm;
        static const ydk::Enum::YLeaf ios_encaps_type_atm_dxi;
        static const ydk::Enum::YLeaf ios_encaps_type_fr_ietf;
        static const ydk::Enum::YLeaf ios_encaps_type_smds_dxi;
        static const ydk::Enum::YLeaf ios_encaps_type_atm_dxi_ietf;
        static const ydk::Enum::YLeaf ios_encaps_type_channel;
        static const ydk::Enum::YLeaf ios_encaps_type_sdlc;
        static const ydk::Enum::YLeaf ios_encaps_type_sde;
        static const ydk::Enum::YLeaf ios_encaps_type_bstun;
        static const ydk::Enum::YLeaf ios_encaps_type_dialer;
        static const ydk::Enum::YLeaf ios_encaps_type_novell_fddi;
        static const ydk::Enum::YLeaf ios_encaps_type_v120;
        static const ydk::Enum::YLeaf ios_encaps_type_isl;
        static const ydk::Enum::YLeaf ios_encaps_type_loop;
        static const ydk::Enum::YLeaf ios_encaps_type_channel_ilan;
        static const ydk::Enum::YLeaf ios_encaps_type_serial_autodetect;
        static const ydk::Enum::YLeaf ios_encaps_type_cpp;
        static const ydk::Enum::YLeaf ios_encaps_type_ndlc;
        static const ydk::Enum::YLeaf ios_encaps_type_lapd;
        static const ydk::Enum::YLeaf ios_encaps_type_ftc_trunk;
        static const ydk::Enum::YLeaf ios_encaps_type_atmces_t1;
        static const ydk::Enum::YLeaf ios_encaps_type_atmces_e1;
        static const ydk::Enum::YLeaf ios_encaps_type_voice;
        static const ydk::Enum::YLeaf ios_encaps_type_alc;
        static const ydk::Enum::YLeaf ios_encaps_type_uts;
        static const ydk::Enum::YLeaf ios_encaps_type_trisl;
        static const ydk::Enum::YLeaf ios_encaps_type_mcns;
        static const ydk::Enum::YLeaf ios_encaps_type_atmces;
        static const ydk::Enum::YLeaf ios_encaps_type_trans;
        static const ydk::Enum::YLeaf ios_encaps_type_clear_channel;
        static const ydk::Enum::YLeaf ios_encaps_type_tc_atm;
        static const ydk::Enum::YLeaf ios_encaps_type_fr_ppp;
        static const ydk::Enum::YLeaf ios_encaps_type_dot1q;
        static const ydk::Enum::YLeaf ios_encaps_type_funi;
        static const ydk::Enum::YLeaf ios_encaps_type_lapbta;
        static const ydk::Enum::YLeaf ios_encaps_type_docsis;
        static const ydk::Enum::YLeaf ios_encaps_type_np_inband;
        static const ydk::Enum::YLeaf ios_encaps_type_ss7_mtp2;
        static const ydk::Enum::YLeaf ios_encaps_type_gtp;
        static const ydk::Enum::YLeaf ios_encaps_type_isl_switchport;
        static const ydk::Enum::YLeaf ios_encaps_type_srp;
        static const ydk::Enum::YLeaf ios_encaps_type_ppp_etype;
        static const ydk::Enum::YLeaf ios_encaps_type_atm_ppp;
        static const ydk::Enum::YLeaf ios_encaps_type_mfr;
        static const ydk::Enum::YLeaf ios_encaps_type_srp2;
        static const ydk::Enum::YLeaf ios_encaps_type_fr_extended;
        static const ydk::Enum::YLeaf ios_encaps_type_pppoe;
        static const ydk::Enum::YLeaf ios_encaps_type_ouni_sdcc;
        static const ydk::Enum::YLeaf ios_encaps_type_multiservice;
        static const ydk::Enum::YLeaf ios_encaps_type_container;
        static const ydk::Enum::YLeaf ios_encaps_type_dot1ad;
        static const ydk::Enum::YLeaf ios_encaps_type_cem;
        static const ydk::Enum::YLeaf ios_encaps_type_dot1ah;
        static const ydk::Enum::YLeaf ios_encaps_type_ptp;
        static const ydk::Enum::YLeaf ios_encaps_type_ssl;
        static const ydk::Enum::YLeaf ios_encaps_type_lisp;
        static const ydk::Enum::YLeaf ios_encaps_type_dsp_spa;
        static const ydk::Enum::YLeaf ios_encaps_type_t101;
        static const ydk::Enum::YLeaf ios_encaps_type_crypto;
        static const ydk::Enum::YLeaf ios_encaps_type_rawtcp;
        static const ydk::Enum::YLeaf ios_encaps_type_async;
        static const ydk::Enum::YLeaf ios_encaps_type_cmd;
        static const ydk::Enum::YLeaf ios_encaps_type_scada;
        static const ydk::Enum::YLeaf ios_encaps_type_rawudp;
        static const ydk::Enum::YLeaf ios_encaps_type_relay_line;
        static const ydk::Enum::YLeaf ios_encaps_type_rawmpls;
        static const ydk::Enum::YLeaf ios_encaps_type_arpa_nid;

        static int get_enum_value(const std::string & name) {
            if (name == "ios-encaps-type-null") return 0;
            if (name == "ios-encaps-type-arpa") return 1;
            if (name == "ios-encaps-type-sap") return 2;
            if (name == "ios-encaps-type-snap") return 3;
            if (name == "ios-encaps-type-1822") return 4;
            if (name == "ios-encaps-type-hdlc") return 5;
            if (name == "ios-encaps-type-unused2") return 6;
            if (name == "ios-encaps-type-unused1") return 7;
            if (name == "ios-encaps-type-lapb") return 8;
            if (name == "ios-encaps-type-x25") return 9;
            if (name == "ios-encaps-type-hub") return 10;
            if (name == "ios-encaps-type-novell-ether") return 11;
            if (name == "ios-encaps-type-unsupported") return 12;
            if (name == "ios-encaps-type-3com-tr") return 13;
            if (name == "ios-encaps-type-ub-tr") return 14;
            if (name == "ios-encaps-type-apollo") return 15;
            if (name == "ios-encaps-type-ppp") return 16;
            if (name == "ios-encaps-type-unused4") return 17;
            if (name == "ios-encaps-type-vines-tr") return 18;
            if (name == "ios-encaps-type-ethertalk") return 19;
            if (name == "ios-encaps-type-frame-relay") return 20;
            if (name == "ios-encaps-type-smds") return 21;
            if (name == "ios-encaps-type-mac") return 22;
            if (name == "ios-encaps-type-ultra-iso2") return 23;
            if (name == "ios-encaps-type-ultra-iso1") return 24;
            if (name == "ios-encaps-type-stun") return 25;
            if (name == "ios-encaps-type-bridge") return 26;
            if (name == "ios-encaps-type-llc2") return 27;
            if (name == "ios-encaps-type-sdlcp") return 28;
            if (name == "ios-encaps-type-sdlcs") return 29;
            if (name == "ios-encaps-type-slip") return 30;
            if (name == "ios-encaps-type-tunnel") return 31;
            if (name == "ios-encaps-type-bridge-encaps") return 32;
            if (name == "ios-encaps-type-atm") return 33;
            if (name == "ios-encaps-type-atm-dxi") return 34;
            if (name == "ios-encaps-type-fr-ietf") return 35;
            if (name == "ios-encaps-type-smds-dxi") return 36;
            if (name == "ios-encaps-type-atm-dxi-ietf") return 37;
            if (name == "ios-encaps-type-channel") return 38;
            if (name == "ios-encaps-type-sdlc") return 39;
            if (name == "ios-encaps-type-sde") return 40;
            if (name == "ios-encaps-type-bstun") return 41;
            if (name == "ios-encaps-type-dialer") return 42;
            if (name == "ios-encaps-type-novell-fddi") return 43;
            if (name == "ios-encaps-type-v120") return 44;
            if (name == "ios-encaps-type-isl") return 45;
            if (name == "ios-encaps-type-loop") return 46;
            if (name == "ios-encaps-type-channel-ilan") return 47;
            if (name == "ios-encaps-type-serial-autodetect") return 48;
            if (name == "ios-encaps-type-cpp") return 49;
            if (name == "ios-encaps-type-ndlc") return 50;
            if (name == "ios-encaps-type-lapd") return 51;
            if (name == "ios-encaps-type-ftc-trunk") return 52;
            if (name == "ios-encaps-type-atmces-t1") return 53;
            if (name == "ios-encaps-type-atmces-e1") return 54;
            if (name == "ios-encaps-type-voice") return 55;
            if (name == "ios-encaps-type-alc") return 56;
            if (name == "ios-encaps-type-uts") return 57;
            if (name == "ios-encaps-type-trisl") return 58;
            if (name == "ios-encaps-type-mcns") return 59;
            if (name == "ios-encaps-type-atmces") return 60;
            if (name == "ios-encaps-type-trans") return 61;
            if (name == "ios-encaps-type-clear-channel") return 62;
            if (name == "ios-encaps-type-tc-atm") return 63;
            if (name == "ios-encaps-type-fr-ppp") return 64;
            if (name == "ios-encaps-type-dot1q") return 65;
            if (name == "ios-encaps-type-funi") return 66;
            if (name == "ios-encaps-type-lapbta") return 67;
            if (name == "ios-encaps-type-docsis") return 68;
            if (name == "ios-encaps-type-np-inband") return 69;
            if (name == "ios-encaps-type-ss7-mtp2") return 70;
            if (name == "ios-encaps-type-gtp") return 71;
            if (name == "ios-encaps-type-isl-switchport") return 72;
            if (name == "ios-encaps-type-srp") return 73;
            if (name == "ios-encaps-type-ppp-etype") return 74;
            if (name == "ios-encaps-type-atm-ppp") return 75;
            if (name == "ios-encaps-type-mfr") return 76;
            if (name == "ios-encaps-type-srp2") return 77;
            if (name == "ios-encaps-type-fr-extended") return 78;
            if (name == "ios-encaps-type-pppoe") return 79;
            if (name == "ios-encaps-type-ouni-sdcc") return 80;
            if (name == "ios-encaps-type-multiservice") return 81;
            if (name == "ios-encaps-type-container") return 82;
            if (name == "ios-encaps-type-dot1ad") return 83;
            if (name == "ios-encaps-type-cem") return 84;
            if (name == "ios-encaps-type-dot1ah") return 85;
            if (name == "ios-encaps-type-ptp") return 86;
            if (name == "ios-encaps-type-ssl") return 87;
            if (name == "ios-encaps-type-lisp") return 88;
            if (name == "ios-encaps-type-dsp-spa") return 89;
            if (name == "ios-encaps-type-t101") return 90;
            if (name == "ios-encaps-type-crypto") return 91;
            if (name == "ios-encaps-type-rawtcp") return 92;
            if (name == "ios-encaps-type-async") return 93;
            if (name == "ios-encaps-type-cmd") return 94;
            if (name == "ios-encaps-type-scada") return 95;
            if (name == "ios-encaps-type-rawudp") return 96;
            if (name == "ios-encaps-type-relay-line") return 97;
            if (name == "ios-encaps-type-rawmpls") return 98;
            if (name == "ios-encaps-type-arpa-nid") return 99;
            return -1;
        }
};


}
}

#endif /* _CISCO_IOS_XE_IOS_COMMON_OPER_ */

