#ifndef _IANAIFTYPE_MIB_
#define _IANAIFTYPE_MIB_

#include <memory>
#include <vector>
#include <string>
#include <ydk/types.hpp>
#include <ydk/errors.hpp>

namespace cisco_ios_xe {
namespace IANAifType_MIB {

class IANAtunnelType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf other;
        static const ydk::Enum::YLeaf direct;
        static const ydk::Enum::YLeaf gre;
        static const ydk::Enum::YLeaf minimal;
        static const ydk::Enum::YLeaf l2tp;
        static const ydk::Enum::YLeaf pptp;
        static const ydk::Enum::YLeaf l2f;
        static const ydk::Enum::YLeaf udp;
        static const ydk::Enum::YLeaf atmp;
        static const ydk::Enum::YLeaf msdp;
        static const ydk::Enum::YLeaf sixToFour;
        static const ydk::Enum::YLeaf sixOverFour;
        static const ydk::Enum::YLeaf isatap;
        static const ydk::Enum::YLeaf teredo;

        static int get_enum_value(const std::string & name) {
            if (name == "other") return 1;
            if (name == "direct") return 2;
            if (name == "gre") return 3;
            if (name == "minimal") return 4;
            if (name == "l2tp") return 5;
            if (name == "pptp") return 6;
            if (name == "l2f") return 7;
            if (name == "udp") return 8;
            if (name == "atmp") return 9;
            if (name == "msdp") return 10;
            if (name == "sixToFour") return 11;
            if (name == "sixOverFour") return 12;
            if (name == "isatap") return 13;
            if (name == "teredo") return 14;
            return -1;
        }
};

class IANAifType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf other;
        static const ydk::Enum::YLeaf regular1822;
        static const ydk::Enum::YLeaf hdh1822;
        static const ydk::Enum::YLeaf ddnX25;
        static const ydk::Enum::YLeaf rfc877x25;
        static const ydk::Enum::YLeaf ethernetCsmacd;
        static const ydk::Enum::YLeaf iso88023Csmacd;
        static const ydk::Enum::YLeaf iso88024TokenBus;
        static const ydk::Enum::YLeaf iso88025TokenRing;
        static const ydk::Enum::YLeaf iso88026Man;
        static const ydk::Enum::YLeaf starLan;
        static const ydk::Enum::YLeaf proteon10Mbit;
        static const ydk::Enum::YLeaf proteon80Mbit;
        static const ydk::Enum::YLeaf hyperchannel;
        static const ydk::Enum::YLeaf fddi;
        static const ydk::Enum::YLeaf lapb;
        static const ydk::Enum::YLeaf sdlc;
        static const ydk::Enum::YLeaf ds1;
        static const ydk::Enum::YLeaf e1;
        static const ydk::Enum::YLeaf basicISDN;
        static const ydk::Enum::YLeaf primaryISDN;
        static const ydk::Enum::YLeaf propPointToPointSerial;
        static const ydk::Enum::YLeaf ppp;
        static const ydk::Enum::YLeaf softwareLoopback;
        static const ydk::Enum::YLeaf eon;
        static const ydk::Enum::YLeaf ethernet3Mbit;
        static const ydk::Enum::YLeaf nsip;
        static const ydk::Enum::YLeaf slip;
        static const ydk::Enum::YLeaf ultra;
        static const ydk::Enum::YLeaf ds3;
        static const ydk::Enum::YLeaf sip;
        static const ydk::Enum::YLeaf frameRelay;
        static const ydk::Enum::YLeaf rs232;
        static const ydk::Enum::YLeaf para;
        static const ydk::Enum::YLeaf arcnet;
        static const ydk::Enum::YLeaf arcnetPlus;
        static const ydk::Enum::YLeaf atm;
        static const ydk::Enum::YLeaf miox25;
        static const ydk::Enum::YLeaf sonet;
        static const ydk::Enum::YLeaf x25ple;
        static const ydk::Enum::YLeaf iso88022llc;
        static const ydk::Enum::YLeaf localTalk;
        static const ydk::Enum::YLeaf smdsDxi;
        static const ydk::Enum::YLeaf frameRelayService;
        static const ydk::Enum::YLeaf v35;
        static const ydk::Enum::YLeaf hssi;
        static const ydk::Enum::YLeaf hippi;
        static const ydk::Enum::YLeaf modem;
        static const ydk::Enum::YLeaf aal5;
        static const ydk::Enum::YLeaf sonetPath;
        static const ydk::Enum::YLeaf sonetVT;
        static const ydk::Enum::YLeaf smdsIcip;
        static const ydk::Enum::YLeaf propVirtual;
        static const ydk::Enum::YLeaf propMultiplexor;
        static const ydk::Enum::YLeaf ieee80212;
        static const ydk::Enum::YLeaf fibreChannel;
        static const ydk::Enum::YLeaf hippiInterface;
        static const ydk::Enum::YLeaf frameRelayInterconnect;
        static const ydk::Enum::YLeaf aflane8023;
        static const ydk::Enum::YLeaf aflane8025;
        static const ydk::Enum::YLeaf cctEmul;
        static const ydk::Enum::YLeaf fastEther;
        static const ydk::Enum::YLeaf isdn;
        static const ydk::Enum::YLeaf v11;
        static const ydk::Enum::YLeaf v36;
        static const ydk::Enum::YLeaf g703at64k;
        static const ydk::Enum::YLeaf g703at2mb;
        static const ydk::Enum::YLeaf qllc;
        static const ydk::Enum::YLeaf fastEtherFX;
        static const ydk::Enum::YLeaf channel;
        static const ydk::Enum::YLeaf ieee80211;
        static const ydk::Enum::YLeaf ibm370parChan;
        static const ydk::Enum::YLeaf escon;
        static const ydk::Enum::YLeaf dlsw;
        static const ydk::Enum::YLeaf isdns;
        static const ydk::Enum::YLeaf isdnu;
        static const ydk::Enum::YLeaf lapd;
        static const ydk::Enum::YLeaf ipSwitch;
        static const ydk::Enum::YLeaf rsrb;
        static const ydk::Enum::YLeaf atmLogical;
        static const ydk::Enum::YLeaf ds0;
        static const ydk::Enum::YLeaf ds0Bundle;
        static const ydk::Enum::YLeaf bsc;
        static const ydk::Enum::YLeaf async;
        static const ydk::Enum::YLeaf cnr;
        static const ydk::Enum::YLeaf iso88025Dtr;
        static const ydk::Enum::YLeaf eplrs;
        static const ydk::Enum::YLeaf arap;
        static const ydk::Enum::YLeaf propCnls;
        static const ydk::Enum::YLeaf hostPad;
        static const ydk::Enum::YLeaf termPad;
        static const ydk::Enum::YLeaf frameRelayMPI;
        static const ydk::Enum::YLeaf x213;
        static const ydk::Enum::YLeaf adsl;
        static const ydk::Enum::YLeaf radsl;
        static const ydk::Enum::YLeaf sdsl;
        static const ydk::Enum::YLeaf vdsl;
        static const ydk::Enum::YLeaf iso88025CRFPInt;
        static const ydk::Enum::YLeaf myrinet;
        static const ydk::Enum::YLeaf voiceEM;
        static const ydk::Enum::YLeaf voiceFXO;
        static const ydk::Enum::YLeaf voiceFXS;
        static const ydk::Enum::YLeaf voiceEncap;
        static const ydk::Enum::YLeaf voiceOverIp;
        static const ydk::Enum::YLeaf atmDxi;
        static const ydk::Enum::YLeaf atmFuni;
        static const ydk::Enum::YLeaf atmIma;
        static const ydk::Enum::YLeaf pppMultilinkBundle;
        static const ydk::Enum::YLeaf ipOverCdlc;
        static const ydk::Enum::YLeaf ipOverClaw;
        static const ydk::Enum::YLeaf stackToStack;
        static const ydk::Enum::YLeaf virtualIpAddress;
        static const ydk::Enum::YLeaf mpc;
        static const ydk::Enum::YLeaf ipOverAtm;
        static const ydk::Enum::YLeaf iso88025Fiber;
        static const ydk::Enum::YLeaf tdlc;
        static const ydk::Enum::YLeaf gigabitEthernet;
        static const ydk::Enum::YLeaf hdlc;
        static const ydk::Enum::YLeaf lapf;
        static const ydk::Enum::YLeaf v37;
        static const ydk::Enum::YLeaf x25mlp;
        static const ydk::Enum::YLeaf x25huntGroup;
        static const ydk::Enum::YLeaf trasnpHdlc;
        static const ydk::Enum::YLeaf interleave;
        static const ydk::Enum::YLeaf fast;
        static const ydk::Enum::YLeaf ip;
        static const ydk::Enum::YLeaf docsCableMaclayer;
        static const ydk::Enum::YLeaf docsCableDownstream;
        static const ydk::Enum::YLeaf docsCableUpstream;
        static const ydk::Enum::YLeaf a12MppSwitch;
        static const ydk::Enum::YLeaf tunnel;
        static const ydk::Enum::YLeaf coffee;
        static const ydk::Enum::YLeaf ces;
        static const ydk::Enum::YLeaf atmSubInterface;
        static const ydk::Enum::YLeaf l2vlan;
        static const ydk::Enum::YLeaf l3ipvlan;
        static const ydk::Enum::YLeaf l3ipxvlan;
        static const ydk::Enum::YLeaf digitalPowerline;
        static const ydk::Enum::YLeaf mediaMailOverIp;
        static const ydk::Enum::YLeaf dtm;
        static const ydk::Enum::YLeaf dcn;
        static const ydk::Enum::YLeaf ipForward;
        static const ydk::Enum::YLeaf msdsl;
        static const ydk::Enum::YLeaf ieee1394;
        static const ydk::Enum::YLeaf if_gsn;
        static const ydk::Enum::YLeaf dvbRccMacLayer;
        static const ydk::Enum::YLeaf dvbRccDownstream;
        static const ydk::Enum::YLeaf dvbRccUpstream;
        static const ydk::Enum::YLeaf atmVirtual;
        static const ydk::Enum::YLeaf mplsTunnel;
        static const ydk::Enum::YLeaf srp;
        static const ydk::Enum::YLeaf voiceOverAtm;
        static const ydk::Enum::YLeaf voiceOverFrameRelay;
        static const ydk::Enum::YLeaf idsl;
        static const ydk::Enum::YLeaf compositeLink;
        static const ydk::Enum::YLeaf ss7SigLink;
        static const ydk::Enum::YLeaf propWirelessP2P;
        static const ydk::Enum::YLeaf frForward;
        static const ydk::Enum::YLeaf rfc1483;
        static const ydk::Enum::YLeaf usb;
        static const ydk::Enum::YLeaf ieee8023adLag;
        static const ydk::Enum::YLeaf bgppolicyaccounting;
        static const ydk::Enum::YLeaf frf16MfrBundle;
        static const ydk::Enum::YLeaf h323Gatekeeper;
        static const ydk::Enum::YLeaf h323Proxy;
        static const ydk::Enum::YLeaf mpls;
        static const ydk::Enum::YLeaf mfSigLink;
        static const ydk::Enum::YLeaf hdsl2;
        static const ydk::Enum::YLeaf shdsl;
        static const ydk::Enum::YLeaf ds1FDL;
        static const ydk::Enum::YLeaf pos;
        static const ydk::Enum::YLeaf dvbAsiIn;
        static const ydk::Enum::YLeaf dvbAsiOut;
        static const ydk::Enum::YLeaf plc;
        static const ydk::Enum::YLeaf nfas;
        static const ydk::Enum::YLeaf tr008;
        static const ydk::Enum::YLeaf gr303RDT;
        static const ydk::Enum::YLeaf gr303IDT;
        static const ydk::Enum::YLeaf isup;
        static const ydk::Enum::YLeaf propDocsWirelessMaclayer;
        static const ydk::Enum::YLeaf propDocsWirelessDownstream;
        static const ydk::Enum::YLeaf propDocsWirelessUpstream;
        static const ydk::Enum::YLeaf hiperlan2;
        static const ydk::Enum::YLeaf propBWAp2Mp;
        static const ydk::Enum::YLeaf sonetOverheadChannel;
        static const ydk::Enum::YLeaf digitalWrapperOverheadChannel;
        static const ydk::Enum::YLeaf aal2;
        static const ydk::Enum::YLeaf radioMAC;
        static const ydk::Enum::YLeaf atmRadio;
        static const ydk::Enum::YLeaf imt;
        static const ydk::Enum::YLeaf mvl;
        static const ydk::Enum::YLeaf reachDSL;
        static const ydk::Enum::YLeaf frDlciEndPt;
        static const ydk::Enum::YLeaf atmVciEndPt;
        static const ydk::Enum::YLeaf opticalChannel;
        static const ydk::Enum::YLeaf opticalTransport;
        static const ydk::Enum::YLeaf propAtm;
        static const ydk::Enum::YLeaf voiceOverCable;
        static const ydk::Enum::YLeaf infiniband;
        static const ydk::Enum::YLeaf teLink;
        static const ydk::Enum::YLeaf q2931;
        static const ydk::Enum::YLeaf virtualTg;
        static const ydk::Enum::YLeaf sipTg;
        static const ydk::Enum::YLeaf sipSig;
        static const ydk::Enum::YLeaf docsCableUpstreamChannel;
        static const ydk::Enum::YLeaf econet;
        static const ydk::Enum::YLeaf pon155;
        static const ydk::Enum::YLeaf pon622;
        static const ydk::Enum::YLeaf bridge;
        static const ydk::Enum::YLeaf linegroup;
        static const ydk::Enum::YLeaf voiceEMFGD;
        static const ydk::Enum::YLeaf voiceFGDEANA;
        static const ydk::Enum::YLeaf voiceDID;
        static const ydk::Enum::YLeaf mpegTransport;
        static const ydk::Enum::YLeaf sixToFour;
        static const ydk::Enum::YLeaf gtp;
        static const ydk::Enum::YLeaf pdnEtherLoop1;
        static const ydk::Enum::YLeaf pdnEtherLoop2;
        static const ydk::Enum::YLeaf opticalChannelGroup;
        static const ydk::Enum::YLeaf homepna;
        static const ydk::Enum::YLeaf gfp;
        static const ydk::Enum::YLeaf ciscoISLvlan;
        static const ydk::Enum::YLeaf actelisMetaLOOP;
        static const ydk::Enum::YLeaf fcipLink;
        static const ydk::Enum::YLeaf rpr;
        static const ydk::Enum::YLeaf qam;
        static const ydk::Enum::YLeaf lmp;
        static const ydk::Enum::YLeaf cblVectaStar;
        static const ydk::Enum::YLeaf docsCableMCmtsDownstream;
        static const ydk::Enum::YLeaf adsl2;
        static const ydk::Enum::YLeaf macSecControlledIF;
        static const ydk::Enum::YLeaf macSecUncontrolledIF;
        static const ydk::Enum::YLeaf aviciOpticalEther;
        static const ydk::Enum::YLeaf atmbond;
        static const ydk::Enum::YLeaf voiceFGDOS;
        static const ydk::Enum::YLeaf mocaVersion1;
        static const ydk::Enum::YLeaf ieee80216WMAN;
        static const ydk::Enum::YLeaf adsl2plus;
        static const ydk::Enum::YLeaf dvbRcsMacLayer;
        static const ydk::Enum::YLeaf dvbTdm;
        static const ydk::Enum::YLeaf dvbRcsTdma;
        static const ydk::Enum::YLeaf x86Laps;
        static const ydk::Enum::YLeaf wwanPP;
        static const ydk::Enum::YLeaf wwanPP2;
        static const ydk::Enum::YLeaf voiceEBS;
        static const ydk::Enum::YLeaf ifPwType;
        static const ydk::Enum::YLeaf ilan;
        static const ydk::Enum::YLeaf pip;
        static const ydk::Enum::YLeaf aluELP;
        static const ydk::Enum::YLeaf gpon;
        static const ydk::Enum::YLeaf vdsl2;
        static const ydk::Enum::YLeaf capwapDot11Profile;
        static const ydk::Enum::YLeaf capwapDot11Bss;
        static const ydk::Enum::YLeaf capwapWtpVirtualRadio;
        static const ydk::Enum::YLeaf bits;
        static const ydk::Enum::YLeaf docsCableUpstreamRfPort;
        static const ydk::Enum::YLeaf cableDownstreamRfPort;
        static const ydk::Enum::YLeaf vmwareVirtualNic;
        static const ydk::Enum::YLeaf ieee802154;
        static const ydk::Enum::YLeaf otnOdu;
        static const ydk::Enum::YLeaf otnOtu;
        static const ydk::Enum::YLeaf ifVfiType;
        static const ydk::Enum::YLeaf g9981;
        static const ydk::Enum::YLeaf g9982;
        static const ydk::Enum::YLeaf g9983;
        static const ydk::Enum::YLeaf aluEpon;
        static const ydk::Enum::YLeaf aluEponOnu;
        static const ydk::Enum::YLeaf aluEponPhysicalUni;
        static const ydk::Enum::YLeaf aluEponLogicalLink;
        static const ydk::Enum::YLeaf aluGponOnu;
        static const ydk::Enum::YLeaf aluGponPhysicalUni;
        static const ydk::Enum::YLeaf vmwareNicTeam;
        static const ydk::Enum::YLeaf docsOfdmDownstream;
        static const ydk::Enum::YLeaf docsOfdmaUpstream;
        static const ydk::Enum::YLeaf gfast;
        static const ydk::Enum::YLeaf sdci;
        static const ydk::Enum::YLeaf xboxWireless;
        static const ydk::Enum::YLeaf fastdsl;
        static const ydk::Enum::YLeaf docsCableScte55d1FwdOob;
        static const ydk::Enum::YLeaf docsCableScte55d1RetOob;
        static const ydk::Enum::YLeaf docsCableScte55d2DsOob;
        static const ydk::Enum::YLeaf docsCableScte55d2UsOob;
        static const ydk::Enum::YLeaf docsCableNdf;
        static const ydk::Enum::YLeaf docsCableNdr;

        static int get_enum_value(const std::string & name) {
            if (name == "other") return 1;
            if (name == "regular1822") return 2;
            if (name == "hdh1822") return 3;
            if (name == "ddnX25") return 4;
            if (name == "rfc877x25") return 5;
            if (name == "ethernetCsmacd") return 6;
            if (name == "iso88023Csmacd") return 7;
            if (name == "iso88024TokenBus") return 8;
            if (name == "iso88025TokenRing") return 9;
            if (name == "iso88026Man") return 10;
            if (name == "starLan") return 11;
            if (name == "proteon10Mbit") return 12;
            if (name == "proteon80Mbit") return 13;
            if (name == "hyperchannel") return 14;
            if (name == "fddi") return 15;
            if (name == "lapb") return 16;
            if (name == "sdlc") return 17;
            if (name == "ds1") return 18;
            if (name == "e1") return 19;
            if (name == "basicISDN") return 20;
            if (name == "primaryISDN") return 21;
            if (name == "propPointToPointSerial") return 22;
            if (name == "ppp") return 23;
            if (name == "softwareLoopback") return 24;
            if (name == "eon") return 25;
            if (name == "ethernet3Mbit") return 26;
            if (name == "nsip") return 27;
            if (name == "slip") return 28;
            if (name == "ultra") return 29;
            if (name == "ds3") return 30;
            if (name == "sip") return 31;
            if (name == "frameRelay") return 32;
            if (name == "rs232") return 33;
            if (name == "para") return 34;
            if (name == "arcnet") return 35;
            if (name == "arcnetPlus") return 36;
            if (name == "atm") return 37;
            if (name == "miox25") return 38;
            if (name == "sonet") return 39;
            if (name == "x25ple") return 40;
            if (name == "iso88022llc") return 41;
            if (name == "localTalk") return 42;
            if (name == "smdsDxi") return 43;
            if (name == "frameRelayService") return 44;
            if (name == "v35") return 45;
            if (name == "hssi") return 46;
            if (name == "hippi") return 47;
            if (name == "modem") return 48;
            if (name == "aal5") return 49;
            if (name == "sonetPath") return 50;
            if (name == "sonetVT") return 51;
            if (name == "smdsIcip") return 52;
            if (name == "propVirtual") return 53;
            if (name == "propMultiplexor") return 54;
            if (name == "ieee80212") return 55;
            if (name == "fibreChannel") return 56;
            if (name == "hippiInterface") return 57;
            if (name == "frameRelayInterconnect") return 58;
            if (name == "aflane8023") return 59;
            if (name == "aflane8025") return 60;
            if (name == "cctEmul") return 61;
            if (name == "fastEther") return 62;
            if (name == "isdn") return 63;
            if (name == "v11") return 64;
            if (name == "v36") return 65;
            if (name == "g703at64k") return 66;
            if (name == "g703at2mb") return 67;
            if (name == "qllc") return 68;
            if (name == "fastEtherFX") return 69;
            if (name == "channel") return 70;
            if (name == "ieee80211") return 71;
            if (name == "ibm370parChan") return 72;
            if (name == "escon") return 73;
            if (name == "dlsw") return 74;
            if (name == "isdns") return 75;
            if (name == "isdnu") return 76;
            if (name == "lapd") return 77;
            if (name == "ipSwitch") return 78;
            if (name == "rsrb") return 79;
            if (name == "atmLogical") return 80;
            if (name == "ds0") return 81;
            if (name == "ds0Bundle") return 82;
            if (name == "bsc") return 83;
            if (name == "async") return 84;
            if (name == "cnr") return 85;
            if (name == "iso88025Dtr") return 86;
            if (name == "eplrs") return 87;
            if (name == "arap") return 88;
            if (name == "propCnls") return 89;
            if (name == "hostPad") return 90;
            if (name == "termPad") return 91;
            if (name == "frameRelayMPI") return 92;
            if (name == "x213") return 93;
            if (name == "adsl") return 94;
            if (name == "radsl") return 95;
            if (name == "sdsl") return 96;
            if (name == "vdsl") return 97;
            if (name == "iso88025CRFPInt") return 98;
            if (name == "myrinet") return 99;
            if (name == "voiceEM") return 100;
            if (name == "voiceFXO") return 101;
            if (name == "voiceFXS") return 102;
            if (name == "voiceEncap") return 103;
            if (name == "voiceOverIp") return 104;
            if (name == "atmDxi") return 105;
            if (name == "atmFuni") return 106;
            if (name == "atmIma") return 107;
            if (name == "pppMultilinkBundle") return 108;
            if (name == "ipOverCdlc") return 109;
            if (name == "ipOverClaw") return 110;
            if (name == "stackToStack") return 111;
            if (name == "virtualIpAddress") return 112;
            if (name == "mpc") return 113;
            if (name == "ipOverAtm") return 114;
            if (name == "iso88025Fiber") return 115;
            if (name == "tdlc") return 116;
            if (name == "gigabitEthernet") return 117;
            if (name == "hdlc") return 118;
            if (name == "lapf") return 119;
            if (name == "v37") return 120;
            if (name == "x25mlp") return 121;
            if (name == "x25huntGroup") return 122;
            if (name == "trasnpHdlc") return 123;
            if (name == "interleave") return 124;
            if (name == "fast") return 125;
            if (name == "ip") return 126;
            if (name == "docsCableMaclayer") return 127;
            if (name == "docsCableDownstream") return 128;
            if (name == "docsCableUpstream") return 129;
            if (name == "a12MppSwitch") return 130;
            if (name == "tunnel") return 131;
            if (name == "coffee") return 132;
            if (name == "ces") return 133;
            if (name == "atmSubInterface") return 134;
            if (name == "l2vlan") return 135;
            if (name == "l3ipvlan") return 136;
            if (name == "l3ipxvlan") return 137;
            if (name == "digitalPowerline") return 138;
            if (name == "mediaMailOverIp") return 139;
            if (name == "dtm") return 140;
            if (name == "dcn") return 141;
            if (name == "ipForward") return 142;
            if (name == "msdsl") return 143;
            if (name == "ieee1394") return 144;
            if (name == "if-gsn") return 145;
            if (name == "dvbRccMacLayer") return 146;
            if (name == "dvbRccDownstream") return 147;
            if (name == "dvbRccUpstream") return 148;
            if (name == "atmVirtual") return 149;
            if (name == "mplsTunnel") return 150;
            if (name == "srp") return 151;
            if (name == "voiceOverAtm") return 152;
            if (name == "voiceOverFrameRelay") return 153;
            if (name == "idsl") return 154;
            if (name == "compositeLink") return 155;
            if (name == "ss7SigLink") return 156;
            if (name == "propWirelessP2P") return 157;
            if (name == "frForward") return 158;
            if (name == "rfc1483") return 159;
            if (name == "usb") return 160;
            if (name == "ieee8023adLag") return 161;
            if (name == "bgppolicyaccounting") return 162;
            if (name == "frf16MfrBundle") return 163;
            if (name == "h323Gatekeeper") return 164;
            if (name == "h323Proxy") return 165;
            if (name == "mpls") return 166;
            if (name == "mfSigLink") return 167;
            if (name == "hdsl2") return 168;
            if (name == "shdsl") return 169;
            if (name == "ds1FDL") return 170;
            if (name == "pos") return 171;
            if (name == "dvbAsiIn") return 172;
            if (name == "dvbAsiOut") return 173;
            if (name == "plc") return 174;
            if (name == "nfas") return 175;
            if (name == "tr008") return 176;
            if (name == "gr303RDT") return 177;
            if (name == "gr303IDT") return 178;
            if (name == "isup") return 179;
            if (name == "propDocsWirelessMaclayer") return 180;
            if (name == "propDocsWirelessDownstream") return 181;
            if (name == "propDocsWirelessUpstream") return 182;
            if (name == "hiperlan2") return 183;
            if (name == "propBWAp2Mp") return 184;
            if (name == "sonetOverheadChannel") return 185;
            if (name == "digitalWrapperOverheadChannel") return 186;
            if (name == "aal2") return 187;
            if (name == "radioMAC") return 188;
            if (name == "atmRadio") return 189;
            if (name == "imt") return 190;
            if (name == "mvl") return 191;
            if (name == "reachDSL") return 192;
            if (name == "frDlciEndPt") return 193;
            if (name == "atmVciEndPt") return 194;
            if (name == "opticalChannel") return 195;
            if (name == "opticalTransport") return 196;
            if (name == "propAtm") return 197;
            if (name == "voiceOverCable") return 198;
            if (name == "infiniband") return 199;
            if (name == "teLink") return 200;
            if (name == "q2931") return 201;
            if (name == "virtualTg") return 202;
            if (name == "sipTg") return 203;
            if (name == "sipSig") return 204;
            if (name == "docsCableUpstreamChannel") return 205;
            if (name == "econet") return 206;
            if (name == "pon155") return 207;
            if (name == "pon622") return 208;
            if (name == "bridge") return 209;
            if (name == "linegroup") return 210;
            if (name == "voiceEMFGD") return 211;
            if (name == "voiceFGDEANA") return 212;
            if (name == "voiceDID") return 213;
            if (name == "mpegTransport") return 214;
            if (name == "sixToFour") return 215;
            if (name == "gtp") return 216;
            if (name == "pdnEtherLoop1") return 217;
            if (name == "pdnEtherLoop2") return 218;
            if (name == "opticalChannelGroup") return 219;
            if (name == "homepna") return 220;
            if (name == "gfp") return 221;
            if (name == "ciscoISLvlan") return 222;
            if (name == "actelisMetaLOOP") return 223;
            if (name == "fcipLink") return 224;
            if (name == "rpr") return 225;
            if (name == "qam") return 226;
            if (name == "lmp") return 227;
            if (name == "cblVectaStar") return 228;
            if (name == "docsCableMCmtsDownstream") return 229;
            if (name == "adsl2") return 230;
            if (name == "macSecControlledIF") return 231;
            if (name == "macSecUncontrolledIF") return 232;
            if (name == "aviciOpticalEther") return 233;
            if (name == "atmbond") return 234;
            if (name == "voiceFGDOS") return 235;
            if (name == "mocaVersion1") return 236;
            if (name == "ieee80216WMAN") return 237;
            if (name == "adsl2plus") return 238;
            if (name == "dvbRcsMacLayer") return 239;
            if (name == "dvbTdm") return 240;
            if (name == "dvbRcsTdma") return 241;
            if (name == "x86Laps") return 242;
            if (name == "wwanPP") return 243;
            if (name == "wwanPP2") return 244;
            if (name == "voiceEBS") return 245;
            if (name == "ifPwType") return 246;
            if (name == "ilan") return 247;
            if (name == "pip") return 248;
            if (name == "aluELP") return 249;
            if (name == "gpon") return 250;
            if (name == "vdsl2") return 251;
            if (name == "capwapDot11Profile") return 252;
            if (name == "capwapDot11Bss") return 253;
            if (name == "capwapWtpVirtualRadio") return 254;
            if (name == "bits") return 255;
            if (name == "docsCableUpstreamRfPort") return 256;
            if (name == "cableDownstreamRfPort") return 257;
            if (name == "vmwareVirtualNic") return 258;
            if (name == "ieee802154") return 259;
            if (name == "otnOdu") return 260;
            if (name == "otnOtu") return 261;
            if (name == "ifVfiType") return 262;
            if (name == "g9981") return 263;
            if (name == "g9982") return 264;
            if (name == "g9983") return 265;
            if (name == "aluEpon") return 266;
            if (name == "aluEponOnu") return 267;
            if (name == "aluEponPhysicalUni") return 268;
            if (name == "aluEponLogicalLink") return 269;
            if (name == "aluGponOnu") return 270;
            if (name == "aluGponPhysicalUni") return 271;
            if (name == "vmwareNicTeam") return 272;
            if (name == "docsOfdmDownstream") return 277;
            if (name == "docsOfdmaUpstream") return 278;
            if (name == "gfast") return 279;
            if (name == "sdci") return 280;
            if (name == "xboxWireless") return 281;
            if (name == "fastdsl") return 282;
            if (name == "docsCableScte55d1FwdOob") return 283;
            if (name == "docsCableScte55d1RetOob") return 284;
            if (name == "docsCableScte55d2DsOob") return 285;
            if (name == "docsCableScte55d2UsOob") return 286;
            if (name == "docsCableNdf") return 287;
            if (name == "docsCableNdr") return 288;
            return -1;
        }
};


}
}

#endif /* _IANAIFTYPE_MIB_ */

