#include "generated_entity_lookup.hpp"
#include <ydk/entity_lookup.hpp>
#include <ydk/path_api.hpp>

namespace openconfig
{

void openconfig_augment_lookup_tables()
{

    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-if-ethernet"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-restconf-monitoring"},"2016-08-15", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-transport-types"},"2016-06-17", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-yang-smiv2"},"2012-06-22", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-diffserv-policy"},"2015-04-07", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-rib-bgp"},"2016-04-11", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-netconf"},"2011-06-01", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-netconf-notifications"},"2012-02-06", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-lacp"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-platform"},"2016-06-06", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-extensions"},"2015-10-09", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-event-notifications"},"2016-10-27", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-routing-policy"},"2016-05-12", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-syslog-types"},"2015-11-09", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-interfaces"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-static"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-ip"},"2014-06-16", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-key-chain"},"2015-02-24", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-ospf"},"2015-03-09", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-inet-types"},"2013-07-15", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-common-structure"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-netconf-monitoring"},"2010-10-04", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-if-ip"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-yang-push"},"2016-10-28", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-te"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-routing"},"2015-05-25", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-yang-library"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-if-aggregate"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-local-routing"},"2016-05-11", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-platform-types"},"2016-06-06", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-common"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-rsvp"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-ipv4-unicast-routing"},"2015-05-25", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"iana-crypt-hash"},"2014-08-06", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-policy-types"},"2016-05-12", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-diffserv-action"},"2015-04-07", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-interfaces-ext"},"", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-vlan"},"2016-05-26", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-types"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-diffserv-classifier"},"2015-04-07", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-yang-types"},"2013-07-15", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-telemetry"},"2016-02-04", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"policy-types"},"2013-10-07", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"cisco-xr-openconfig-interfaces-types"},"2016-10-12", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-ldp"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-platform-transceiver"},"2016-05-24", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-igp"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-types"},"2016-05-31", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-interfaces"},"2014-05-08", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"iana-if-type"},"2014-05-08", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-policy"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-sr"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-terminal-device"},"2016-06-17", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-neighbor"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-common-multiprotocol"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-global"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-bgp-peer-group"},"2016-06-21", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-rib-bgp-types"},"2016-04-11", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-netconf-with-defaults"},"2011-06-01", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-ipv6-unicast-routing"},"2015-05-25", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-mpls-types"},"2015-11-05", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"ietf-diffserv-target"},"2015-04-07", {}, {}});
    ydk::ydk_global_capabilities.push_back(ydk::path::Capability{std::string{"openconfig-vlan-types"},"2016-05-26", {}, {}});

}


std::map<std::pair<std::string, std::string>, std::string> openconfig_namespace_identity_lookup {
    { {"mpegTransport", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ifPwType", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"channel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluGponOnu", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableUpstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mocaVersion1", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"g703at2mb", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"econet", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hippi", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"adsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceEncap", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"g703at64k", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"otnOtu", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbRccUpstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fibreChannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"transpHdlc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"lapf", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbTdm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"teLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gigabitEthernet", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ces", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ipSwitch", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"nsip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fastEther", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dcn", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"slip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sonetVT", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"radsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"g9981", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmbond", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hostPad", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"qam", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propMultiplexor", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"digitalWrapperOverheadChannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"wwanPP2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gtp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"h323Proxy", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"v36", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"v35", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceFXO", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sdlc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"capwapDot11Bss", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pos", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hiperlan2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"rfc877x25", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceFGDOS", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceOverCable", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aal5", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"x213", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceDID", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"plc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frDlciEndPt", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"tunnel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableDownstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"cctEmul", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ds0", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"h323Gatekeeper", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableMCmtsDownstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmVirtual", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pon622", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"opticalChannelGroup", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmSubInterface", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gr303IDT", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"lapb", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sdsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"miox25", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"capwapWtpVirtualRadio", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propDocsWirelessUpstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frameRelay", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluEponOnu", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"idsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceOverAtm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceFGDEANA", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frf16MfrBundle", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sonetPath", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"srp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceEM", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gpon", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"softwareLoopback", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"localTalk", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"shdsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"capwapDot11Profile", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee80211", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frameRelayInterconnect", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmVciEndPt", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sonet", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88025Dtr", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ppp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mvl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"isdn", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluEponPhysicalUni", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88022llc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmLogical", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ds1", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"tdlc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluELP", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"usb", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pppMultilinkBundle", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"q2931", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aflane8025", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceEMFGD", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"macSecControlledIF", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmRadio", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ethernetCsmacd", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee802154", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fddi", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"modem", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"g9982", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ilan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"msdsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"if-gsn", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"actelisMetaLOOP", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aflane8023", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fast", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbRccMacLayer", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88025Fiber", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mfSigLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dlsw", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"para", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"coffee", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ss7SigLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sonetOverheadChannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"x25huntGroup", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbRcsTdma", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"bsc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee80212", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"bgppolicyaccounting", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"v37", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ipOverCdlc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"homepna", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"arcnet", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hippiInterface", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hyperchannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ds1FDL", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbAsiOut", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pon155", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ultra", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frameRelayService", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propBWAp2Mp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"vmwareNicTeam", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee80216WMAN", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"regular1822", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"wwanPP", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"arcnetPlus", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"stackToStack", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hdh1822", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"async", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"starLan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"x86Laps", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"l3ipxvlan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"smdsDxi", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"otnOdu", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sixToFour", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propAtm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"opticalChannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"adsl2plus", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"lapd", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88026Man", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propVirtual", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gr303RDT", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hssi", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ibm370parChan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"isup", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"macSecUncontrolledIF", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"vmwareVirtualNic", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ddnX25", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"linegroup", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"radioMAC", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"rsrb", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"virtualIpAddress", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fcipLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"nfas", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"x25ple", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"rpr", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aal2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluEpon", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"eplrs", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbRcsMacLayer", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"x25mlp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableUpstreamChannel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceOverIp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ethernet3Mbit", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableMaclayer", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"cblVectaStar", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"rfc1483", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hdsl2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"docsCableUpstreamRfPort", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"tr008", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ciscoISLvlan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"eon", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dtm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ipOverAtm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"reachDSL", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"isdnu", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"vdsl2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"escon", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"interleave", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbRccDownstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"vdsl", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluEponLogicalLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ds0Bundle", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"v11", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"qllc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"gfp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mpls", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ds3", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceEBS", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mplsTunnel", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aviciOpticalEther", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"proteon10Mbit", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"cableDownstreamRfPort", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"basicISDN", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"proteon80Mbit", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"termPad", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propCnls", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mediaMailOverIp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"isdns", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee8023adLag", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceFXS", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propDocsWirelessDownstream", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sipSig", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"adsl2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atm", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"primaryISDN", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"a12MppSwitch", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"fastEtherFX", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"aluGponPhysicalUni", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"other", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pdnEtherLoop2", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"bits", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ipOverClaw", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"virtualTg", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frameRelayMPI", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88025CRFPInt", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88024TokenBus", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"g9983", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"l3ipvlan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"e1", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propPointToPointSerial", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propWirelessP2P", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmFuni", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"opticalTransport", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"dvbAsiIn", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ifVfiType", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"rs232", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmDxi", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"imt", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"atmIma", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"smdsIcip", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"propDocsWirelessMaclayer", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"voiceOverFrameRelay", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"cnr", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"digitalPowerline", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ieee1394", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"ipForward", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"infiniband", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"myrinet", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"pdnEtherLoop1", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"sipTg", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88025TokenRing", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"l2vlan", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iana-interface-type", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"mpc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"compositeLink", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"bridge", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"iso88023Csmacd", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"arap", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"hdlc", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"frForward", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"lmp", "urn:ietf:params:xml:ns:yang:iana-if-type"},  "iana-if-type"},
    { {"meter-action-type", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"always-drop", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"algorithmic-drop", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"tail-drop", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"meter-action-set", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"random-detect", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"meter-action-drop", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"priority", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"meter", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"marking", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"max-rate", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"drop-type", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"min-rate", "urn:ietf:params:xml:ns:yang:ietf-diffserv-action"},  "ietf-diffserv-action"},
    { {"protocol", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"dscp", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"source-port", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"filter-type", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"classifier-entry-filter-operation-type", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"match-any-filter", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"match-all-filter", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"destination-port", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"source-ip-address", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"destination-ip-address", "urn:ietf:params:xml:ns:yang:ietf-diffserv-classifier"},  "ietf-diffserv-classifier"},
    { {"action-type", "urn:ietf:params:xml:ns:yang:ietf-diffserv-policy"},  "ietf-diffserv-policy"},
    { {"inbound", "urn:ietf:params:xml:ns:yang:ietf-diffserv-target"},  "ietf-diffserv-target"},
    { {"direction", "urn:ietf:params:xml:ns:yang:ietf-diffserv-target"},  "ietf-diffserv-target"},
    { {"outbound", "urn:ietf:params:xml:ns:yang:ietf-diffserv-target"},  "ietf-diffserv-target"},
    { {"error", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"error-insufficient-resources", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"subscription-stream-status", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"active", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"inactive", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"ok", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"encodings", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"encode-json", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"stream", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"subscription-deleted", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"subscription-errors", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"netconf", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"NETCONF", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"no-resources", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"error-configured-subscription", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"subscription-result", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"in-error", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"suspended", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"internal-error", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"transport", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"error-no-such-subscription", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"other", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"error-no-such-option", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"error-other", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"encode-xml", "urn:ietf:params:xml:ns:yang:ietf-event-notifications"},  "ietf-event-notifications"},
    { {"interface-type", "urn:ietf:params:xml:ns:yang:ietf-interfaces"},  "ietf-interfaces"},
    { {"ipv4-unicast", "urn:ietf:params:xml:ns:yang:ietf-ipv4-unicast-routing"},  "ietf-ipv4-unicast-routing"},
    { {"ipv6-unicast", "urn:ietf:params:xml:ns:yang:ietf-ipv6-unicast-routing"},  "ietf-ipv6-unicast-routing"},
    { {"yin", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"xsd", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"transport", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"rnc", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"netconf-soap-over-https", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"netconf-ssh", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"yang", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"netconf-tls", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"netconf-soap-over-beep", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"schema-format", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"netconf-beep", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"rng", "urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"},  "ietf-netconf-monitoring"},
    { {"stub", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"if-link-type", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"nssa", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"area-type", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"ospf", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"if-link-type-normal", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"ospfv2", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"if-link-type-sham-link", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"normal", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"operation-mode", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"ships-in-the-night", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"if-link-type-virtual-link", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"ospfv3", "urn:ietf:params:xml:ns:yang:ietf-ospf"},  "ietf-ospf"},
    { {"vrf-routing-instance", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"default-routing-instance", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"routing-instance", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"static", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"direct", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"routing-protocol", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"address-family", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"ipv6", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"ipv4", "urn:ietf:params:xml:ns:yang:ietf-routing"},  "ietf-routing"},
    { {"local5", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local4", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"console", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local2", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"mail", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local1", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"syslog", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"ftp", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local0", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"audit", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"syslog-facility", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"ntp", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"uucp", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"authpriv", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"lpr", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"cron", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local7", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local3", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"local6", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"news", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"auth", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"cron2", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"daemon", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"kern", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"user", "urn:ietf:params:xml:ns:yang:ietf-syslog-types"},  "ietf-syslog-types"},
    { {"error-data-not-authorized", "urn:ietf:params:xml:ns:yang:ietf-yang-push"},  "ietf-yang-push"},
    { {"custom-stream", "urn:ietf:params:xml:ns:yang:ietf-yang-push"},  "ietf-yang-push"},
    { {"http2", "urn:ietf:params:xml:ns:yang:ietf-yang-push"},  "ietf-yang-push"},
    { {"yang-push", "urn:ietf:params:xml:ns:yang:ietf-yang-push"},  "ietf-yang-push"},
    { {"object-identity", "urn:ietf:params:xml:ns:yang:ietf-yang-smiv2"},  "ietf-yang-smiv2"},
    { {"GRACEFUL_RESTART", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"ASN32", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L3VPN_IPV6_MULTICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"REMOVE_PRIVATE_AS_OPTION", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"IPV6_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"MPBGP", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"NO_EXPORT_SUBCONFED", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"IPV4_LABELED_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"BGP_WELL_KNOWN_STD_COMMUNITY", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L3VPN_IPV4_MULTICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"NO_EXPORT", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"BGP_CAPABILITY", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"NO_ADVERTISE", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"PRIVATE_AS_REMOVE_ALL", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"IPV4_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"IPV6_LABELED_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"PRIVATE_AS_REPLACE_ALL", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"NOPEER", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L2VPN_VPLS", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L3VPN_IPV4_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L2VPN_EVPN", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"L3VPN_IPV6_UNICAST", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"AFI_SAFI_TYPE", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"ADD_PATHS", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"ROUTE_REFRESH", "http://openconfig.net/yang/bgp-types"},  "openconfig-bgp-types"},
    { {"SPEED_10GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_25GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_1GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_UNKNOWN", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_40GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_10MB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_100GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_50GB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"SPEED_100MB", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"ETHERNET_SPEED", "http://openconfig.net/yang/interfaces/ethernet"},  "openconfig-if-ethernet"},
    { {"LOCAL_DEFINED_NEXT_HOP", "http://openconfig.net/yang/local-routing"},  "openconfig-local-routing"},
    { {"LOCAL_LINK", "http://openconfig.net/yang/local-routing"},  "openconfig-local-routing"},
    { {"DROP", "http://openconfig.net/yang/local-routing"},  "openconfig-local-routing"},
    { {"explicitly-defined", "http://openconfig.net/yang/mpls"},  "openconfig-mpls"},
    { {"path-computation-method", "http://openconfig.net/yang/mpls"},  "openconfig-mpls"},
    { {"externally-queried", "http://openconfig.net/yang/mpls"},  "openconfig-mpls"},
    { {"locally-computed", "http://openconfig.net/yang/mpls"},  "openconfig-mpls"},
    { {"tunnel-admin-status", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"path-setup-protocol", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"unprotected", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"IMPLICIT", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"P2MP", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"EXPLICIT", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"path-setup-rsvp", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"INGRESS", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"tunnel-type", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"null-label-type", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"lsp-role", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"ADMIN_UP", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"path-setup-ldp", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"ADMIN_DOWN", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"TRANSIT", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"DOWN", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"EGRESS", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"P2P", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"link-node-protection-requested", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"UP", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"link-protection-requested", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"protection-type", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"lsp-oper-status", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"path-setup-sr", "http://openconfig.net/yang/mpls-types"},  "openconfig-mpls-types"},
    { {"OPENCONFIG_HARDWARE_COMPONENT", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"BACKPLANE", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"CPU", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"POWER_SUPPLY", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"MODULE", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"PORT", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"SENSOR", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"CHASSIS", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"OPERATING_SYSTEM", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"FAN", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"OPENCONFIG_SOFTWARE_COMPONENT", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"LINECARD", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"TRANSCEIVER", "http://openconfig.net/yang/platform-types"},  "openconfig-platform-types"},
    { {"DIRECTLY_CONNECTED", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"INSTALL_PROTOCOL_TYPE", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"STATIC", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"ATTRIBUTE_LE", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"ATTRIBUTE_COMPARISON", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"ISIS", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"OSPF", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"ATTRIBUTE_EQ", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"ATTRIBUTE_GE", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"LOCAL_AGGREGATE", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"OSPF3", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"BGP", "http://openconfig.net/yang/policy-types"},  "openconfig-policy-types"},
    { {"BGP_NOT_SELECTED_BESTPATH", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"INVALID_ROUTE_REASON", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"LOCAL_PREF_LOWER", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"PREFER_EXTERNAL", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"REJECTED_IMPORT_POLICY", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"INVALID_CLUSTER_LOOP", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"AS_PATH_LONGER", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"BGP_NOT_SELECTED_POLICY", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"HIGHER_PEER_ADDRESS", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"NEXTHOP_COST_HIGHER", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"INVALID_ORIGINATOR", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"MED_HIGHER", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"INVALID_AS_LOOP", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"HIGHER_ROUTER_ID", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"INVALID_CONFED", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"ORIGIN_TYPE_HIGHER", "http://openconfig.net/yang/rib/bgp-types"},  "openconfig-rib-bgp-types"},
    { {"P1L1_2D1", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIB_RATE_100G", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_40GBASE_SR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"XFP", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"P1S1_2D2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_ODU2E", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_100G_MLG", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_ER4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTN", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTU2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"VSR2000_3R3", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_10GBASE_ER", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100G_AOC", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_10GBASE_ZR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_UNDEFINED", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTU3", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_40GE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_CWDM4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_STM16", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_ETHERNET", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_40GBASE_ER4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_SR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_10GBASE_SR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_LR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_PSM4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"P1L1_2D2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIB_RATE_1G", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_ODU4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIB_RATE_2.5G", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"SONET_UNDEFINED", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_40GBASE_LR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_SR10", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"OPTICAL_CHANNEL", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_4X10GBASE_SR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"SC_CONNECTOR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"NON_PLUGGABLE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_4X10GBASE_LR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"SONET_APPLICATION_CODE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OC768", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"X2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRANSCEIVER_FORM_FACTOR_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"FIBER_CONNECTOR_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIBUTARY_PROTOCOL_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OC48", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_CLR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_100GE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"SFP", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"QSFP28", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"MPO_CONNECTOR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100G_ACC", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_10GE_LAN", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_1GE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"CFP", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"CFP2_ACO", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"CFP2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIB_RATE_10G", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTU4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_10GBASE_LR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIBUTARY_RATE_CLASS_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"CFP4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_10GE_WAN", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"TRIB_RATE_40G", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETHERNET_PMD_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_100GBASE_CR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"OTN_APPLICATION_CODE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"QSFP", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_ODU3", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTUCN", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_40GBASE_PSM4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"OTHER", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"VSR2000_3R2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_STM256", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"LC_CONNECTOR", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"LOGICAL_ELEMENT_PROTOCOL_TYPE", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_STM64", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_ODU2", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_40GBASE_CR4", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTU2E", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"ETH_10GBASE_LRM", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OC192", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"VSR2000_3R5", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"OTN_UNDEFINED", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"PROT_OTU1E", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"SFP_PLUS", "http://openconfig.net/yang/transport-types"},  "openconfig-transport-types"},
    { {"IPV4", "http://openconfig.net/yang/openconfig-types"},  "openconfig-types"},
    { {"IPV6", "http://openconfig.net/yang/openconfig-types"},  "openconfig-types"},
    { {"ADDRESS_FAMILY", "http://openconfig.net/yang/openconfig-types"},  "openconfig-types"},
    { {"TPID_0x8A88", "http://openconfig.net/yang/vlan-types"},  "openconfig-vlan-types"},
    { {"TPID_TYPES", "http://openconfig.net/yang/vlan-types"},  "openconfig-vlan-types"},
    { {"TPID_0x9100", "http://openconfig.net/yang/vlan-types"},  "openconfig-vlan-types"},
    { {"TPID_0x8100", "http://openconfig.net/yang/vlan-types"},  "openconfig-vlan-types"},
    { {"TPID_0X9200", "http://openconfig.net/yang/vlan-types"},  "openconfig-vlan-types"},
    { {"qos-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"appnav-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"atm-clp", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"vlan", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"qos", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"dst-mac", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"wlan-user-priority", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"packet-service", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"security-group-tag", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"perf-mon", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"ipv6-acl", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"cos", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"access-control-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"ipv6-acl-name", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"class-type", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"atm-vci", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"mpls-exp-imp", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"qos-group", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"flow-dlci", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"flow-de", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"dei-inner", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"src-mac", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"access-control", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"input-interface", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"policy-type", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"vlan-inner", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"inspect-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"control", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"security-group-name", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"cos-inner", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"mpls-exp-top", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"inspect", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"service", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"discard-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"control-class", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"appnav", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"flow-record", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"pbr", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"packet-length", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"ipv4-acl", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"application", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"class-map", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"metadata", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"vpls", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"flow-ip", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"dei", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"prec", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"ip-rtp", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
    { {"ipv4-acl-name", "urn:ietf:params:xml:ns:yang:c3pl-types"},  "policy-types"},
};

}

